
###
POST  http://localhost:7300/status/ HTTP/1.1
content-type: application/json

{
    "orderDate": "25/09"
    
}

###
GET  http://localhost:7300/status/ HTTP/1.1

###
GET  http://localhost:7300/status/2 HTTP/1.1

###
PATCH  http://localhost:7300/status/2 HTTP/1.1
content-type: application/json

{
    "password": "tyuvhjbu"
    
}

###
DELETE  http://localhost:7300/status/4 HTTP/1.1
